# --- Voxly Deploy Compose ---

services:

  # --- SERVICES ---
  reclamis:
    image: reclamis:0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/api/health"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      GIN_MODE: release
      RECLAMIS_PORT: ${RECLAMIS_PORT}
      RECLAMIS_LOG_LEVEL: ${RECLAMIS_LOG_LEVEL}
    restart: unless-stopped
